version: "3.9"

services:
  database:
    image: postgres
    container_name: database_hades
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=paulo
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=hades_db
    volumes: 
      - pgdata:/data/postgres
  
volumes: 
  pgdata: 
    driver: local