version: "3.9"

services:
  database:
    image: postgres
    container_name: database_hades
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=paulo
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=hades_db
    volumes: 
      - pgdata:/data/postgres
      
  app:
    build: .
    container_name: hades
    environment: 
      - DATABASE_URL=postgres://paulo:docker@postgres:5432/hades_db
      - PORT=3000
    ports:
      - 3000:3000
      # - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on: 
      - database
    
  
volumes: 
  pgdata: 
    driver: local